Add OWASP ZAP DAST scan

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -180,6 +180,54 @@ jobs:
             k3s/deployment.yaml
 
 
+  dast-scan:
+    runs-on: ubuntu-24.04
+    needs: lint-and-test
+
+    steps:
+      - name: Checkout repository
+        uses: actions/checkout@v4
+
+      - name: Build Docker image for DAST
+        run: |
+          docker build -t devsecops-app:dast .
+
+      - name: Start application
+        run: |
+          docker run -d \
+            --name devsecops-dast \
+            -p 5000:5000 \
+            devsecops-app:dast
+
+      - name: Wait for application
+        run: |
+          for i in {1..30}; do
+            if curl -f http://127.0.0.1:5000/health; then
+              echo "Application is ready"
+              exit 0
+            fi
+
+            echo "Waiting for application..."
+            sleep 2
+          done
+
+          echo "Application failed to start"
+          docker logs devsecops-dast
+          exit 1
+
+      - name: OWASP ZAP Baseline Scan
+        uses: zaproxy/action-baseline@v0.15.0
+        with:
+          target: 'http://127.0.0.1:5000'
+          fail_action: true
+          allow_issue_writing: false
+          artifact_name: zap-report
+
+
+
+
+
+
 
   docker-build-scan-push:
     runs-on: ubuntu-24.04
@@ -190,6 +238,7 @@ jobs:
       - dependency-scan
       - iac-scan
       - policy-as-code
+      - dast-scan
 
     if: always() && github.event_name == 'push'
 
@@ -236,7 +285,8 @@ jobs:
           needs.sast.result == 'success' &&
           needs.dependency-scan.result == 'success' &&
           needs.iac-scan.result == 'success' &&
-          needs.policy-as-code.result == 'success'
+          needs.policy-as-code.result == 'success' &&
+          needs.dast-scan.result == 'success'
         run: |
           echo "${{ secrets.GITHUB_TOKEN }}" | \
           docker login ghcr.io \
@@ -250,6 +300,8 @@ jobs:
           needs.sast.result == 'success' &&
           needs.dependency-scan.result == 'success' &&
           needs.iac-scan.result == 'success' &&
-          needs.policy-as-code.result == 'success'
+          needs.policy-as-code.result == 'success' &&
+          needs.dast-scan.result == 'success'
         run: |
           docker push "${IMAGE_NAME}"
+
